version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dotnet-runtime-and-test-packages:
        patterns:
          - "Microsoft.*"
          - "System.*"
          - "xunit*"
          - "coverlet*"
          - "QuestPDF"
    labels:
      - "dependencies"
      - "dotnet"
    commit-message:
      prefix: "deps(nuget)"
