// Copyright 2026 Ari Sulistiono
// SPDX-License-Identifier: Apache-2.0

using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.IO.Compression;
using System.IO.Ports;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using ARIEC60870.Core.Mapping;
using ARIEC60870.Core.Model;
using ARIEC60870.Desktop.ViewModels;
using ARIEC60870.Desktop.Reporting;
using ARIEC60870.Master;
using ARIEC60870.Master.Model;
using ARIEC60870.Master.Reporting;
using ARIEC60870.Master.Transport;
using Microsoft.Win32;

namespace ARIEC60870.Desktop;

public partial class MainWindow
{
    private string? _lastReportPreviewSignature;
    private bool _reportPreviewRefreshInProgress;
    private int _reportPreviewRevealVersion;
    private static readonly Brush InkBrush = new SolidColorBrush(Color.FromRgb(17, 24, 39));
    private static readonly Brush MutedBrush = new SolidColorBrush(Color.FromRgb(100, 116, 139));
    private static readonly Brush AccentBrush = new SolidColorBrush(Color.FromRgb(37, 99, 235));
    private static readonly Brush GoodBrush = new SolidColorBrush(Color.FromRgb(21, 128, 61));
    private static readonly Brush WarnBrush = new SolidColorBrush(Color.FromRgb(180, 83, 9));
    private static readonly Brush BadBrush = new SolidColorBrush(Color.FromRgb(185, 28, 28));
    private static readonly Brush LineBrush = new SolidColorBrush(Color.FromRgb(219, 229, 242));
    private static readonly Brush PanelBrush = new SolidColorBrush(Color.FromRgb(248, 251, 255));
    private string AppendEvidenceRetentionPolicy(string markdown)
    {
        var builder = new StringBuilder(markdown ?? string.Empty);
        if (builder.Length > 0 && !builder.ToString().EndsWith(Environment.NewLine, StringComparison.Ordinal))
        {
            builder.AppendLine();
        }

        builder.AppendLine();
        builder.AppendLine("## Evidence Retention / UI Store Policy");
        builder.AppendLine();
        foreach (var line in BuildEvidenceRetentionPolicyLines())
        {
            builder.AppendLine("- " + line);
        }

        builder.AppendLine();
        builder.AppendLine("> This section is generated by the UI runtime. It describes evidence retention, trace suppression, low-value compression, and dispatcher pressure at export time.");
        return builder.ToString();
    }

    private string BuildTextEvidenceRetentionHeader(string exportName)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# ARIEC60870 export integrity marker");
        builder.AppendLine("# Export: " + exportName);
        foreach (var line in BuildEvidenceRetentionPolicyLines())
        {
            builder.AppendLine("# " + line);
        }
        builder.AppendLine("#");
        return builder.ToString();
    }

    private IEnumerable<string> BuildEvidenceRetentionPolicyLines()
    {
        yield return $"Trace mode: {GetTraceVerbosityMode()}";
        yield return $"Trace ring visible/stored: {FrameTraceRows.Count}/{MaxVisibleFrameTraceRows}";
        yield return $"Evidence Ledger ring visible/stored: {EvidenceRows.Count}/{MaxVisibleEvidenceRows}";
        yield return $"Value store visible/keyed limit: {ValueRows.Count}/{MaxVisibleValueRows}";
        yield return $"Events ring visible/stored: {RelayEventRows.Count}/{MaxVisibleRelayEventRows}";
        yield return $"Diagnostics ring visible/stored: {DiagnosticRows.Count}/{MaxVisibleDiagnosticRows}";
        yield return $"Trace verbosity suppressed rows: total={_traceVerbositySuppressedRows}, routine={_traceVerbositySuppressedRoutine}, supervisory={_traceVerbositySuppressedSupervisory}";
        yield return $"Backpressure low-value compression: total={_backpressureDroppedEvents}, ack/no-data={_backpressureDroppedAckNoData}, background-poll={_backpressureDroppedBackgroundPoll}, test/supervisory={_backpressureDroppedTestFrames}, other={_backpressureDroppedOtherLowValue}";
        yield return $"Dispatcher queue: current={_pendingEvidence.Count}, maxObserved={_maxPendingEvidenceDepth}, adaptiveBudget={_lastFlushBudget}";
        yield return $"Dispatcher flush: last={_lastUiFlushMs} ms, max={_maxUiFlushMs} ms, ticks={_uiFlushTicks}, lastProcessed={_lastEvidenceProcessed}+{_lastFindingProcessed}, lastVisibleBatchRows={_lastVisibleBatchRows}";
        yield return $"Protocol proof state: CA={(_proofObservedCa > 0 ? _proofObservedCa.ToString(System.Globalization.CultureInfo.InvariantCulture) : "-")}, GI={_proofGiObserved}, GIComplete={_proofGiCompleted}, GINegative={_proofGiNegative}, Digital={_proofDigitalObserved}, Analog={_proofAnalogObserved}, Command={_proofCommandObserved}, CommandFeedback={_proofCommandFeedbackObserved}";
        yield return $"GI coverage matrix: monitor={_lastMonitorReceivedCount}/{_lastMonitorExpectedCount}, digital={_lastDigitalReceivedCount}/{_lastDigitalExpectedCount}, analog={_lastAnalogReceivedCount}/{_lastAnalogExpectedCount}, other={_lastOtherReceivedCount}/{_lastOtherExpectedCount}, missing={_lastMissingMonitorCount}, missingPreview={_lastMissingMonitorPreview}";
        yield return $"Command mapping coverage: commands={_lastCommandExpectedCount}, feedbackMapped={_lastFeedbackMappedCommandCount}";
        yield return "Protected evidence policy: diagnostics/warnings/errors, mapped values, process values, digital values, GI activity, command ASDUs, ACTCON and ACTTERM are protected from low-value trace compression.";
    }

    private void AddEvidenceRetentionExportMarker(string exportTarget)
    {
        AddUiDiagnostic(
            "Info",
            "Evidence",
            "ARIEC-EVIDENCE-RETENTION-POLICY",
            "Evidence export includes retention policy marker",
            $"{exportTarget} captured TraceMode={GetTraceVerbosityMode()}, traceSkip={_traceVerbositySuppressedRows}, lowValueDropped={_backpressureDroppedEvents}, qMax={_maxPendingEvidenceDepth}, maxFlush={_maxUiFlushMs} ms.",
            "Use this marker when reviewing FAT/SAT evidence so compressed routine trace rows are not mistaken for missing protocol evidence.");
    }



    private bool IsReportPreviewTabActive()
        => MainTabControl?.SelectedIndex == 6;

    private void RefreshReportPreview_Click(object sender, RoutedEventArgs e)
    {
        if (MainTabControl is not null && MainTabControl.SelectedIndex != 6)
        {
            MainTabControl.SelectedIndex = 6;
        }

        RefreshReportPreview(force: true);
    }

    private async void EnsureReportPreviewVisible()
    {
        if (ReportPreviewDocumentViewer?.Document is not null && string.Equals(_lastReportPreviewSignature, BuildReportPreviewSignature(), StringComparison.Ordinal))
        {
            HideReportPreviewLoading(immediate: true);
            await RevealReportPreviewAsync(revealVersion: ++_reportPreviewRevealVersion);
            QueueReportPreviewChromeStateUpdate();
            return;
        }

        RefreshReportPreview(force: false);
    }

    private async void RefreshReportPreview(bool force = false)
    {
        if (_reportPreviewRefreshInProgress || ReportPreviewDocumentViewer is null)
        {
            return;
        }

        var signature = BuildReportPreviewSignature();
        if (!force && ReportPreviewDocumentViewer.Document is not null && string.Equals(_lastReportPreviewSignature, signature, StringComparison.Ordinal))
        {
            HideReportPreviewLoading(immediate: true);
            if (IsReportPreviewTabActive())
            {
                await RevealReportPreviewAsync(revealVersion: ++_reportPreviewRevealVersion);
            }
            else
            {
                PrepareReportPreviewForDeferredReveal();
            }
            QueueReportPreviewChromeStateUpdate();
            return;
        }

        _reportPreviewRefreshInProgress = true;
        var revealVersion = ++_reportPreviewRevealVersion;
        var isActiveReportTab = IsReportPreviewTabActive();

        HideReportPreviewLoading(immediate: true);
        if (isActiveReportTab || ReportPreviewDocumentViewer.Document is null)
        {
            PrepareReportPreviewForDeferredReveal();
        }

        try
        {
            await Dispatcher.InvokeAsync(() => { }, DispatcherPriority.Loaded);
            var model = BuildCurrentReportPreviewModel();
            var document = EvidenceReportPreviewDocumentBuilder.Build(model);
            ReportPreviewDocumentViewer.Document = document;
            ReportPreviewDocumentViewer.UpdateLayout();
            await Dispatcher.InvokeAsync(() => { }, DispatcherPriority.Render);
            await Dispatcher.InvokeAsync(() => { }, DispatcherPriority.ApplicationIdle);
            await Dispatcher.InvokeAsync(() => { }, DispatcherPriority.Render);
            _lastReportPreviewSignature = signature;

            if (isActiveReportTab)
            {
                await RevealReportPreviewAsync(revealVersion: revealVersion);
            }
            else
            {
                PrepareReportPreviewForDeferredReveal();
            }

            QueueReportPreviewChromeStateUpdate();
        }
        catch (Exception ex)
        {
            AddUiDiagnostic("Error", "Report", "ARIEC-REPORT-PREVIEW-FAILED", "Report preview failed", ex.Message, "Export PDF still uses the native PDF engine. Refresh the preview after the session stabilizes.");
            AppendSessionLog("Report preview failed: " + ex.Message);
            ReportPreviewDocumentViewer.Document = EvidenceReportPreviewDocumentBuilder.Build(BuildReportPreviewErrorModel(ex.Message));
            ReportPreviewDocumentViewer.UpdateLayout();
            await Dispatcher.InvokeAsync(() => { }, DispatcherPriority.Render);
            if (IsReportPreviewTabActive())
            {
                await RevealReportPreviewAsync(revealVersion: revealVersion);
            }
            QueueReportPreviewChromeStateUpdate();
        }
        finally
        {
            _reportPreviewRefreshInProgress = false;
        }
    }

    private string BuildReportPreviewSignature()
    {
        static string TailSequence(IEnumerable<EvidenceRow> rows)
        {
            var last = rows.LastOrDefault();
            return last is null ? "-" : last.Sequence.ToString(System.Globalization.CultureInfo.InvariantCulture);
        }

        var setupSignature = string.Join(";", BuildReportCommunicationSetupLines().Select(line => line.Key + "=" + line.Value));
        return string.Join("|",
            "layout-v3-smart-findings",
            EvidenceRows.Count.ToString(System.Globalization.CultureInfo.InvariantCulture),
            FrameTraceRows.Count.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ValueRows.Count.ToString(System.Globalization.CultureInfo.InvariantCulture),
            RelayEventRows.Count.ToString(System.Globalization.CultureInfo.InvariantCulture),
            DiagnosticRows.Count.ToString(System.Globalization.CultureInfo.InvariantCulture),
            CountActionableIssueRows().ToString(System.Globalization.CultureInfo.InvariantCulture),
            setupSignature,
            TailSequence(EvidenceRows),
            TailSequence(FrameTraceRows));
    }

    private void ShowReportPreviewLoading(string message)
    {
        if (ReportPreviewLoadingText is not null)
        {
            ReportPreviewLoadingText.Text = message;
        }
        if (ReportPreviewLoadingOverlay is not null)
        {
            ReportPreviewLoadingOverlay.BeginAnimation(UIElement.OpacityProperty, null);
            ReportPreviewLoadingOverlay.Opacity = 1;
            ReportPreviewLoadingOverlay.Visibility = Visibility.Visible;
        }
    }

    private void HideReportPreviewLoading(bool immediate = false)
    {
        if (ReportPreviewLoadingOverlay is null)
        {
            return;
        }

        ReportPreviewLoadingOverlay.BeginAnimation(UIElement.OpacityProperty, null);
        ReportPreviewLoadingOverlay.Opacity = 0;
        ReportPreviewLoadingOverlay.Visibility = Visibility.Collapsed;
    }

    private void PrepareReportPreviewForDeferredReveal()
    {
        if (ReportPreviewDocumentViewer is null)
        {
            return;
        }

        ReportPreviewDocumentViewer.BeginAnimation(UIElement.OpacityProperty, null);
        ReportPreviewDocumentViewer.Visibility = Visibility.Visible;
        ReportPreviewDocumentViewer.Opacity = 0;
        ReportPreviewDocumentViewer.IsHitTestVisible = false;
        if (ReportPreviewDocumentViewer.RenderTransform is TranslateTransform transform)
        {
            transform.BeginAnimation(TranslateTransform.YProperty, null);
            transform.Y = 3;
        }
    }

    private async System.Threading.Tasks.Task RevealReportPreviewAsync(int revealVersion)
    {
        if (ReportPreviewDocumentViewer is null)
        {
            return;
        }

        PrepareReportPreviewForDeferredReveal();
        await Dispatcher.InvokeAsync(() => { }, DispatcherPriority.Render);
        await System.Threading.Tasks.Task.Delay(100);
        if (revealVersion != _reportPreviewRevealVersion || ReportPreviewDocumentViewer is null)
        {
            return;
        }

        ReportPreviewDocumentViewer.Visibility = Visibility.Visible;
        ReportPreviewDocumentViewer.IsHitTestVisible = true;
        ReportPreviewDocumentViewer.BeginAnimation(UIElement.OpacityProperty, null);
        if (ReportPreviewDocumentViewer.RenderTransform is TranslateTransform transform)
        {
            transform.BeginAnimation(TranslateTransform.YProperty, null);
        }

        var opacity = new System.Windows.Media.Animation.DoubleAnimation
        {
            From = 0,
            To = 1,
            Duration = TimeSpan.FromMilliseconds(110),
            EasingFunction = new System.Windows.Media.Animation.CubicEase { EasingMode = System.Windows.Media.Animation.EasingMode.EaseOut }
        };
        ReportPreviewDocumentViewer.BeginAnimation(UIElement.OpacityProperty, opacity);

        if (ReportPreviewDocumentViewer.RenderTransform is TranslateTransform revealTransform)
        {
            var slide = new System.Windows.Media.Animation.DoubleAnimation
            {
                From = 3,
                To = 0,
                Duration = TimeSpan.FromMilliseconds(110),
                EasingFunction = new System.Windows.Media.Animation.CubicEase { EasingMode = System.Windows.Media.Animation.EasingMode.EaseOut }
            };
            revealTransform.BeginAnimation(TranslateTransform.YProperty, slide);
        }
    }

    private void ReportPreviewPrint_Click(object sender, RoutedEventArgs e)
    {
        if (ReportPreviewDocumentViewer?.Document is null)
        {
            return;
        }

        if (ApplicationCommands.Print.CanExecute(null, ReportPreviewDocumentViewer))
        {
            ApplicationCommands.Print.Execute(null, ReportPreviewDocumentViewer);
        }
        QueueReportPreviewChromeStateUpdate();
    }

    private void ReportPreviewCopy_Click(object sender, RoutedEventArgs e)
    {
        if (ReportPreviewDocumentViewer?.Document is null)
        {
            return;
        }

        if (ApplicationCommands.Copy.CanExecute(null, ReportPreviewDocumentViewer))
        {
            ApplicationCommands.Copy.Execute(null, ReportPreviewDocumentViewer);
        }
        QueueReportPreviewChromeStateUpdate();
    }

    private void ReportPreviewZoomOut_Click(object sender, RoutedEventArgs e)
    {
        if (ReportPreviewDocumentViewer?.Document is null)
        {
            return;
        }

        ReportPreviewDocumentViewer.Zoom = Math.Max(40, ReportPreviewDocumentViewer.Zoom - 10);
        QueueReportPreviewChromeStateUpdate();
    }

    private void ReportPreviewZoomIn_Click(object sender, RoutedEventArgs e)
    {
        if (ReportPreviewDocumentViewer?.Document is null)
        {
            return;
        }

        ReportPreviewDocumentViewer.Zoom = Math.Min(300, ReportPreviewDocumentViewer.Zoom + 10);
        QueueReportPreviewChromeStateUpdate();
    }

    private void ReportPreviewFitWidth_Click(object sender, RoutedEventArgs e)
    {
        if (ReportPreviewDocumentViewer?.Document is null)
        {
            return;
        }

        ReportPreviewDocumentViewer.FitToWidth();
        QueueReportPreviewChromeStateUpdate();
    }

    private void ReportPreviewPreviousPage_Click(object sender, RoutedEventArgs e)
    {
        if (ReportPreviewDocumentViewer?.Document is null)
        {
            return;
        }

        if (NavigationCommands.PreviousPage.CanExecute(null, ReportPreviewDocumentViewer))
        {
            NavigationCommands.PreviousPage.Execute(null, ReportPreviewDocumentViewer);
        }
        QueueReportPreviewChromeStateUpdate();
    }

    private void ReportPreviewNextPage_Click(object sender, RoutedEventArgs e)
    {
        if (ReportPreviewDocumentViewer?.Document is null)
        {
            return;
        }

        if (NavigationCommands.NextPage.CanExecute(null, ReportPreviewDocumentViewer))
        {
            NavigationCommands.NextPage.Execute(null, ReportPreviewDocumentViewer);
        }
        QueueReportPreviewChromeStateUpdate();
    }

    private void QueueReportPreviewChromeStateUpdate()
    {
        Dispatcher.BeginInvoke(new Action(UpdateReportPreviewChromeState), DispatcherPriority.Background);
    }

    private void UpdateReportPreviewChromeState()
    {
        if (ReportPreviewDocumentViewer is null)
        {
            return;
        }

        if (ReportPreviewZoomText is not null)
        {
            ReportPreviewZoomText.Text = Math.Round(ReportPreviewDocumentViewer.Zoom).ToString(System.Globalization.CultureInfo.InvariantCulture) + "%";
        }

        if (ReportPreviewPageText is not null)
        {
            var current = Math.Max(1, ReportPreviewDocumentViewer.MasterPageNumber);
            var total = Math.Max(1, ReportPreviewDocumentViewer.PageCount);
            ReportPreviewPageText.Text = $"Page {current} / {total}";
        }
    }

    private EvidencePdfReportModel BuildCurrentReportPreviewModel()
    {
        var rows = GetCurrentReportRows(out var sourceWorkspace);
        var created = DateTime.Now;
        var previewRows = rows.Count == 0 ? BuildEmptyReportPreviewRows() : rows;
        var source = rows.Count == 0 ? "Preview" : sourceWorkspace;
        return BuildEvidencePdfReportModel("ARIEC-REPORT-PREVIEW", created, previewRows, source);
    }

    private EvidencePdfReportModel BuildReportPreviewErrorModel(string message)
    {
        var row = new EvidenceRow(new CaptureFrameSnapshot
        {
            Sequence = 0,
            Time = "-",
            Direction = "STATE",
            ProtocolName = "ARIEC60870",
            ProtocolMode = "101",
            State = "PreviewError",
            Category = "Report",
            DataClass = "Report",
            Service = "Report preview",
            Address = "-",
            SignalOrAddress = "Report preview failed",
            Value = "-",
            Quality = "-",
            AsduType = "-",
            TypeId = "-",
            Cot = "-",
            CotCode = "-",
            LinkAddress = "-",
            CommonAddress = "-",
            Ioa = "-",
            Acd = "-",
            Dfc = "-",
            RelayTime = "no timestamp",
            ResponseTime = "-",
            Meaning = message,
            Detail = "Export PDF can still be used while the preview issue is investigated.",
            RawHex = "-",
            ProtocolTraceTitle = "Report preview failed",
            ProtocolTraceMeaning = message,
            ProtocolTraceRaw = "RAW -",
            ProtocolTraceMeta = "#0  -  ARIEC60870"
        });

        return BuildEvidencePdfReportModel("ARIEC-REPORT-PREVIEW", DateTime.Now, new[] { row }, "Preview");
    }

    private static IReadOnlyList<EvidenceRow> BuildEmptyReportPreviewRows()
    {
        return new[]
        {
            new EvidenceRow(new CaptureFrameSnapshot
            {
                Sequence = 0,
                Time = "-",
                Direction = "STATE",
                ProtocolName = "ARIEC60870",
                ProtocolMode = "101",
                State = "Preview",
                Category = "Report",
                DataClass = "Report",
                Service = "Report preview",
                Address = "-",
                SignalOrAddress = "No evidence rows",
                Value = "-",
                Quality = "-",
                AsduType = "-",
                TypeId = "-",
                Cot = "-",
                CotCode = "-",
                LinkAddress = "-",
                CommonAddress = "-",
                Ioa = "-",
                Acd = "-",
                Dfc = "-",
                RelayTime = "no timestamp",
                ResponseTime = "-",
                Meaning = "No evidence rows are available yet. Run a session, open capture evidence, or select evidence rows first.",
                Detail = "This generated placeholder keeps the PDF preview pipeline identical to Export PDF.",
                RawHex = "-",
                ProtocolTraceTitle = "Report preview placeholder",
                ProtocolTraceMeaning = "No evidence rows are available yet.",
                ProtocolTraceRaw = "RAW -",
                ProtocolTraceMeta = "#0  -  ARIEC60870"
            })
        };
    }

    private string BuildCurrentReportPreviewText()
    {
        var rows = GetCurrentReportRows(out var sourceWorkspace);
        var created = DateTime.Now;
        if (rows.Count == 0)
        {
            return "ARIEC60870 Evidence Analyzer" + Environment.NewLine +
                   "Report Workspace" + Environment.NewLine + Environment.NewLine +
                   "No evidence rows are available yet." + Environment.NewLine +
                   "Run a session, open a capture, or select evidence rows first." + Environment.NewLine + Environment.NewLine +
                   "Generated: " + created.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
        }

        return BuildEvidencePreviewText("ARIEC-REPORT-PREVIEW", created, rows, sourceWorkspace);
    }

    private string BuildEvidencePreviewText(string reportId, DateTime createdLocal, IReadOnlyList<EvidenceRow> rows, string sourceWorkspace)
    {
        var orderedRows = rows.OrderBy(row => row.Sequence).ToArray();
        var first = orderedRows.First();
        var last = orderedRows.Last();
        var verdict = BuildReportVerdict(orderedRows);
        var framesSha256 = ComputeSha256(BuildCaptureFramesJsonl(orderedRows));
        var importantRows = orderedRows.Where(IsReportImportantEvidenceRow).Take(30).ToArray();
        if (importantRows.Length == 0)
        {
            importantRows = orderedRows.Take(30).ToArray();
        }

        var builder = new StringBuilder();
        builder.AppendLine("ARIEC60870 Evidence Analyzer");
        builder.AppendLine("IEC 60870 Evidence Report");
        builder.AppendLine("Professional protocol evidence summary for commissioning, FAT/SAT review, troubleshooting, and handover records.");
        builder.AppendLine();
        builder.AppendLine("Verdict: " + verdict.Status);
        builder.AppendLine(verdict.Summary);
        builder.AppendLine();
        builder.AppendLine("Report");
        builder.AppendLine("  Report ID       : " + reportId);
        builder.AppendLine("  Created         : " + createdLocal.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture));
        builder.AppendLine("  Source          : " + sourceWorkspace);
        builder.AppendLine("  Protocol        : " + GetSelectedProtocolMode());
        builder.AppendLine("  Rows            : " + orderedRows.Length.ToString(System.Globalization.CultureInfo.InvariantCulture));
        builder.AppendLine("  Sequence        : " + first.Sequence + " → " + last.Sequence);
        builder.AppendLine("  Frames SHA256   : " + framesSha256);
        builder.AppendLine();
        builder.AppendLine("Session Counters");
        builder.AppendLine("  TX / RX         : " + _txCount + " / " + _rxCount);
        builder.AppendLine("  GI              : " + _giCount.ToString(System.Globalization.CultureInfo.InvariantCulture));
        builder.AppendLine("  Class 1 / 2     : " + _class1Count + " / " + _class2Count);
        builder.AppendLine("  No data         : " + _noDataCount.ToString(System.Globalization.CultureInfo.InvariantCulture));
        builder.AppendLine("  Event           : " + _dpiCount.ToString(System.Globalization.CultureInfo.InvariantCulture));
        builder.AppendLine("  Issues          : " + CountActionableIssueRows().ToString(System.Globalization.CultureInfo.InvariantCulture));
        builder.AppendLine();
        builder.AppendLine("Important Protocol Evidence");
        foreach (var row in importantRows)
        {
            builder.AppendLine("  #" + row.Sequence.ToString(System.Globalization.CultureInfo.InvariantCulture) +
                " · " + row.Time +
                " · " + row.Direction +
                " · " + row.ProtocolService +
                " · " + ResolvePreviewMeaning(row));
        }

        builder.AppendLine();
        builder.AppendLine("Export PDF for the formatted evidence report.");
        return builder.ToString();
    }

    private FlowDocument BuildCurrentReportPreviewDocument(string previewPdfPath)
    {
        var document = CreatePreviewDocument();
        var text = BuildCurrentReportPreviewText() + Environment.NewLine + "Preview PDF generated: " + previewPdfPath;
        var paragraph = new Paragraph(new Run(text))
        {
            FontFamily = new FontFamily("Cascadia Mono, Consolas, Segoe UI, Arial"),
            FontSize = 12.2,
            Foreground = InkBrush,
            Margin = new Thickness(0),
            LineHeight = 18
        };
        document.Blocks.Add(paragraph);
        return document;
    }

    private FlowDocument BuildReportPreviewErrorDocument(string message)
    {
        var document = CreatePreviewDocument();
        document.Blocks.Add(PreviewParagraph("PDF preview unavailable", 20, FontWeights.SemiBold, BadBrush, 10));
        document.Blocks.Add(PreviewParagraph(message, 12.5, FontWeights.Normal, MutedBrush, 12));
        document.Blocks.Add(PreviewParagraph("Export PDF still uses the native PDF engine. Refresh after the session stabilizes.", 12.5, FontWeights.Normal, MutedBrush, 0));
        return document;
    }

    private FlowDocument CreatePreviewDocument()
    {
        return new FlowDocument
        {
            FontFamily = new FontFamily("Aptos, Segoe UI, Arial"),
            FontSize = 12,
            Foreground = InkBrush,
            Background = Brushes.White,
            PagePadding = new Thickness(4, 4, 18, 18),
            ColumnWidth = 10000
        };
    }

    private FlowDocument BuildEmptyReportPreviewDocument(DateTime createdLocal)
    {
        var document = CreatePreviewDocument();
        document.Blocks.Add(PreviewParagraph("ARIEC60870 Evidence Analyzer", 10, FontWeights.Bold, AccentBrush, 3, characterSpacing: true));
        document.Blocks.Add(PreviewParagraph("Report Workspace", 25, FontWeights.SemiBold, InkBrush, 8));
        document.Blocks.Add(PreviewParagraph("No evidence rows are available yet. Run a session, open a capture, or select evidence rows first.", 12.5, FontWeights.Normal, MutedBrush, 16));
        AddPreviewKeyValues(document, "Generated", new[]
        {
            new KeyValuePair<string, string>("Time", createdLocal.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture)),
            new KeyValuePair<string, string>("Next step", "Run or open capture evidence, then refresh this preview.")
        });
        return document;
    }

    private FlowDocument BuildEvidencePreviewDocument(string reportId, DateTime createdLocal, IReadOnlyList<EvidenceRow> rows, string sourceWorkspace)
    {
        var orderedRows = rows.OrderBy(row => row.Sequence).ToArray();
        var first = orderedRows.First();
        var last = orderedRows.Last();
        var verdict = BuildReportVerdict(orderedRows);
        var framesSha256 = ComputeSha256(BuildCaptureFramesJsonl(orderedRows));
        var document = CreatePreviewDocument();

        document.Blocks.Add(PreviewParagraph("ARIEC60870 EVIDENCE ANALYZER", 10, FontWeights.Bold, AccentBrush, 3, characterSpacing: true));
        document.Blocks.Add(PreviewParagraph("IEC 60870 Evidence Report", 26, FontWeights.SemiBold, InkBrush, 8));
        document.Blocks.Add(PreviewParagraph("Professional protocol evidence summary for commissioning, FAT/SAT review, troubleshooting, and handover records.", 12.5, FontWeights.Normal, MutedBrush, 18));
        document.Blocks.Add(PreviewParagraph("Verdict: " + verdict.Status, 16, FontWeights.SemiBold, verdict.CssClass == "pass" ? GoodBrush : verdict.CssClass == "fail" ? BadBrush : WarnBrush, 14));

        AddPreviewKeyValues(document, "Report", new[]
        {
            new KeyValuePair<string, string>("Report ID", reportId),
            new KeyValuePair<string, string>("Created", createdLocal.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture)),
            new KeyValuePair<string, string>("Source", sourceWorkspace),
            new KeyValuePair<string, string>("Protocol", GetSelectedProtocolMode().ToString()),
            new KeyValuePair<string, string>("Rows", orderedRows.Length.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            new KeyValuePair<string, string>("Sequence", $"{first.Sequence} → {last.Sequence}"),
            new KeyValuePair<string, string>("Frames SHA256", framesSha256)
        });

        AddPreviewKeyValues(document, "Session Counters", new[]
        {
            new KeyValuePair<string, string>("TX / RX", $"{_txCount} / {_rxCount}"),
            new KeyValuePair<string, string>("GI", _giCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            new KeyValuePair<string, string>("Class 1 / Class 2", $"{_class1Count} / {_class2Count}"),
            new KeyValuePair<string, string>("No data", _noDataCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            new KeyValuePair<string, string>("Event", _dpiCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            new KeyValuePair<string, string>("Issues", CountActionableIssueRows().ToString(System.Globalization.CultureInfo.InvariantCulture))
        });

        document.Blocks.Add(PreviewParagraph("Summary Verdict", 16, FontWeights.SemiBold, InkBrush, 6));
        document.Blocks.Add(PreviewParagraph(verdict.Summary, 12.5, FontWeights.Normal, MutedBrush, 14));

        var importantRows = orderedRows.Where(IsReportImportantEvidenceRow).Take(80).ToArray();
        if (importantRows.Length == 0)
        {
            importantRows = orderedRows.Take(80).ToArray();
        }

        AddPreviewRowsTable(document, "Important Protocol Evidence", importantRows);
        AddPreviewRowsTable(document, "Command Evidence", orderedRows.Where(IsCommandEvidenceRow).Take(50).ToArray());
        AddPreviewRowsTable(document, "SOE / Event Evidence", orderedRows.Where(IsSoeOrEventEvidenceRow).Take(60).ToArray());
        return document;
    }

    private static Paragraph PreviewParagraph(string text, double size, FontWeight weight, Brush brush, double bottomMargin, bool characterSpacing = false)
    {
        var paragraph = new Paragraph(new Run(text ?? string.Empty))
        {
            FontSize = size,
            FontWeight = weight,
            Foreground = brush,
            Margin = new Thickness(0, 0, 0, bottomMargin),
            LineHeight = size * 1.45
        };
        return paragraph;
    }

    private void AddPreviewKeyValues(FlowDocument document, string title, IReadOnlyList<KeyValuePair<string, string>> rows)
    {
        document.Blocks.Add(PreviewParagraph(title, 16, FontWeights.SemiBold, InkBrush, 8));
        var table = new Table { CellSpacing = 0, Margin = new Thickness(0, 0, 0, 16) };
        table.Columns.Add(new TableColumn { Width = new GridLength(150) });
        table.Columns.Add(new TableColumn { Width = new GridLength(1, GridUnitType.Star) });
        var group = new TableRowGroup();
        table.RowGroups.Add(group);
        foreach (var item in rows)
        {
            var row = new TableRow();
            row.Cells.Add(PreviewCell(item.Key, FontWeights.SemiBold, MutedBrush, true));
            row.Cells.Add(PreviewCell(item.Value, FontWeights.Normal, InkBrush, false));
            group.Rows.Add(row);
        }
        document.Blocks.Add(table);
    }

    private void AddPreviewRowsTable(FlowDocument document, string title, IReadOnlyList<EvidenceRow> rows)
    {
        document.Blocks.Add(PreviewParagraph(title, 16, FontWeights.SemiBold, InkBrush, 8));
        if (rows.Count == 0)
        {
            document.Blocks.Add(PreviewParagraph("No matching evidence rows in this report scope.", 12, FontWeights.Normal, MutedBrush, 12));
            return;
        }

        var table = new Table { CellSpacing = 0, Margin = new Thickness(0, 0, 0, 18) };
        table.Columns.Add(new TableColumn { Width = new GridLength(60) });
        table.Columns.Add(new TableColumn { Width = new GridLength(92) });
        table.Columns.Add(new TableColumn { Width = new GridLength(78) });
        table.Columns.Add(new TableColumn { Width = new GridLength(128) });
        table.Columns.Add(new TableColumn { Width = new GridLength(1, GridUnitType.Star) });
        var group = new TableRowGroup();
        table.RowGroups.Add(group);
        var header = new TableRow();
        foreach (var heading in new[] { "#", "Time", "Dir", "Service", "Meaning" })
        {
            header.Cells.Add(PreviewCell(heading, FontWeights.SemiBold, MutedBrush, true, PanelBrush));
        }
        group.Rows.Add(header);

        foreach (var item in rows)
        {
            var row = new TableRow();
            row.Cells.Add(PreviewCell(item.Sequence.ToString(System.Globalization.CultureInfo.InvariantCulture), FontWeights.Normal, InkBrush, false));
            row.Cells.Add(PreviewCell(item.Time, FontWeights.Normal, InkBrush, false));
            row.Cells.Add(PreviewCell(item.Direction, FontWeights.SemiBold, AccentBrush, false));
            row.Cells.Add(PreviewCell(item.ProtocolService, FontWeights.Normal, InkBrush, false));
            row.Cells.Add(PreviewCell(ResolvePreviewMeaning(item), FontWeights.Normal, InkBrush, false));
            group.Rows.Add(row);
        }
        document.Blocks.Add(table);
    }


    private static string ResolvePreviewMeaning(EvidenceRow item)
    {
        if (!string.IsNullOrWhiteSpace(item.ProtocolTraceMeaning))
        {
            return item.ProtocolTraceMeaning;
        }

        if (!string.IsNullOrWhiteSpace(item.ReadableMeaning))
        {
            return item.ReadableMeaning;
        }

        if (!string.IsNullOrWhiteSpace(item.OperatorMessage))
        {
            return item.OperatorMessage;
        }

        if (!string.IsNullOrWhiteSpace(item.Summary))
        {
            return item.Summary;
        }

        if (!string.IsNullOrWhiteSpace(item.Detail))
        {
            return item.Detail;
        }

        return item.State;
    }

    private static TableCell PreviewCell(string text, FontWeight weight, Brush brush, bool compact, Brush? background = null)
    {
        var cell = new TableCell(new Paragraph(new Run(text ?? string.Empty))
        {
            FontWeight = weight,
            Foreground = brush,
            FontSize = compact ? 10.5 : 11.5,
            Margin = new Thickness(0),
            LineHeight = compact ? 14 : 16
        })
        {
            Padding = new Thickness(8, compact ? 6 : 7, 8, compact ? 6 : 7),
            BorderBrush = LineBrush,
            BorderThickness = new Thickness(0, 0, 0, 1),
            Background = background ?? Brushes.Transparent
        };
        return cell;
    }

    private IReadOnlyList<EvidenceRow> GetCurrentReportRows(out string sourceWorkspace)
    {
        var selectedRows = GetSelectedRowsForUnifiedEvidenceCapture(out sourceWorkspace);
        if (selectedRows.Count > 0)
        {
            return selectedRows;
        }

        var protocolRows = _protocolTraceStore.Snapshot();
        if (protocolRows.Count > 0)
        {
            sourceWorkspace = "ProtocolTrace";
            return protocolRows;
        }

        if (EvidenceRows.Count > 0)
        {
            sourceWorkspace = "EvidenceSummary";
            return EvidenceRows.ToArray();
        }

        sourceWorkspace = "CurrentEvidenceBuffer";
        return Array.Empty<EvidenceRow>();
    }

    private string BuildCurrentReportPreviewHtml()
    {
        var rows = GetCurrentReportRows(out var sourceWorkspace);
        var created = DateTime.Now;
        if (rows.Count == 0)
        {
            return BuildEmptyReportPreviewHtml(created);
        }

        return BuildEvidenceHtmlReport("ARIEC-REPORT-PREVIEW", created, rows, sourceWorkspace);
    }

    private string BuildEmptyReportPreviewHtml(DateTime createdLocal)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\" />");
        builder.AppendLine("<title>ARIEC Report Workspace</title>");
        builder.AppendLine(BuildReportCss());
        builder.AppendLine("</head><body><main class=\"page\">");
        builder.AppendLine("<section class=\"hero\"><div><div class=\"eyebrow\">ARIEC60870 Evidence Analyzer</div><h1>Report Workspace</h1><p>No evidence rows are available yet. Run an IEC session, open a .ariec capture, or select evidence rows first.</p></div><div class=\"verdict attention\"><span>Status</span><strong>EMPTY</strong></div></section>");
        builder.AppendLine("<section class=\"card\"><h2>How to use</h2><ul><li>Run or open capture evidence.</li><li>Review Values, Events, Trace, or the advanced Evidence Ledger only when needed.</li><li>Return here and click Refresh.</li><li>Click Export PDF to create the professional evidence report.</li></ul></section>");
        builder.AppendLine("<section class=\"card\"><h2>Generated</h2><p>" + EscapeHtml(createdLocal.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture)) + "</p></section>");
        builder.AppendLine("</main></body></html>");
        return builder.ToString();
    }

    private void ExportPdf_Click(object sender, RoutedEventArgs e)
    {
        var rows = GetCurrentReportRows(out var sourceWorkspace);

        if (rows.Count == 0)
        {
            ModernMessageBox.Show(this, "No evidence rows are available yet. Run or open a capture first.", "Export PDF report", MessageBoxButton.OK, MessageBoxImage.Information);
            return;
        }

        var created = DateTime.Now;
        var reportId = "ARIEC-REPORT-" + created.ToString("yyyyMMdd-HHmmss", System.Globalization.CultureInfo.InvariantCulture);
        var dialog = new SaveFileDialog
        {
            Title = "Export professional PDF evidence report",
            Filter = "PDF report (*.pdf)|*.pdf|All files (*.*)|*.*",
            FileName = $"{reportId}.pdf",
            AddExtension = true,
            DefaultExt = ".pdf"
        };

        if (dialog.ShowDialog(this) != true)
        {
            return;
        }

        try
        {
            var model = BuildEvidencePdfReportModel(reportId, created, rows, sourceWorkspace);
            EvidencePdfReportService.Save(dialog.FileName, model);
            AddEvidenceRetentionExportMarker("protocol PDF evidence report");
            AppendSessionLog("protocol PDF evidence report exported: " + dialog.FileName);
            ModernMessageBox.Show(this, "PDF evidence report exported successfully.", "Export PDF report", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            AddUiDiagnostic("Error", "Report", "ARIEC-PDF-EXPORT-FAILED", "PDF report export failed", ex.Message, "Check the output path, file permissions, and whether the target PDF file is already open.");
            ModernMessageBox.Show(this, "PDF export failed: " + ex.Message, "Export PDF report", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private EvidencePdfReportModel BuildEvidencePdfReportModel(string reportId, DateTime createdLocal, IReadOnlyList<EvidenceRow> rows, string sourceWorkspace)
    {
        var orderedRows = rows.OrderBy(row => row.Sequence).ToArray();
        var first = orderedRows.First();
        var last = orderedRows.Last();
        var protocolMode = GetSelectedProtocolMode().ToString();
        var giRows = orderedRows.Where(IsGiEvidenceRow).Take(80).ToArray();
        var commandRows = orderedRows.Where(IsCommandEvidenceRow).Take(80).ToArray();
        var soeRows = orderedRows.Where(IsSoeOrEventEvidenceRow).Take(120).ToArray();
        var importantRows = orderedRows.Where(IsReportImportantEvidenceRow).Take(180).ToArray();
        var framesSha256 = ComputeSha256(BuildCaptureFramesJsonl(orderedRows));
        var communicationSetup = BuildReportCommunicationSetupLines().ToArray();
        var smartFindings = BuildSmartFindingsWithCorrectionTrail(orderedRows, FindingRows.ToArray(), communicationSetup);
        var verdict = BuildReportVerdict(orderedRows, smartFindings);

        return new EvidencePdfReportModel(
            reportId,
            createdLocal,
            sourceWorkspace,
            protocolMode,
            verdict.Status,
            verdict.Summary,
            verdict.CssClass,
            smartFindings,
            new[]
            {
                new KeyValuePair<string, string>("Report ID", reportId),
                new KeyValuePair<string, string>("Created", createdLocal.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture)),
                new KeyValuePair<string, string>("Source", sourceWorkspace),
                new KeyValuePair<string, string>("Protocol", protocolMode),
                new KeyValuePair<string, string>("Rows", orderedRows.Length.ToString(System.Globalization.CultureInfo.InvariantCulture)),
                new KeyValuePair<string, string>("Sequence", $"{first.Sequence} → {last.Sequence}"),
                new KeyValuePair<string, string>("Frames SHA256", framesSha256)
            },
            new[]
            {
                new KeyValuePair<string, string>("TX / RX", $"{_txCount} / {_rxCount}"),
                new KeyValuePair<string, string>("GI", _giCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
                new KeyValuePair<string, string>("Class 1 / Class 2", $"{_class1Count} / {_class2Count}"),
                new KeyValuePair<string, string>("No data", _noDataCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
                new KeyValuePair<string, string>("DPI/Event", _dpiCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
                new KeyValuePair<string, string>("Smart findings", smartFindings.Count.ToString(System.Globalization.CultureInfo.InvariantCulture))
            },
            communicationSetup,
            giRows,
            commandRows,
            soeRows,
            importantRows.Length > 0 ? importantRows : orderedRows.Take(120).ToArray(),
            orderedRows.Length,
            first.Sequence,
            last.Sequence,
            framesSha256);
    }

    private string BuildEvidenceHtmlReport(string reportId, DateTime createdLocal, IReadOnlyList<EvidenceRow> rows, string sourceWorkspace)
    {
        var orderedRows = rows.OrderBy(row => row.Sequence).ToArray();
        var first = orderedRows.First();
        var last = orderedRows.Last();
        var protocolMode = GetSelectedProtocolMode().ToString();
        var setupLines = BuildReportCommunicationSetupLines();
        var giRows = orderedRows.Where(IsGiEvidenceRow).Take(80).ToArray();
        var commandRows = orderedRows.Where(IsCommandEvidenceRow).Take(80).ToArray();
        var soeRows = orderedRows.Where(IsSoeOrEventEvidenceRow).Take(120).ToArray();
        var importantRows = orderedRows.Where(IsReportImportantEvidenceRow).Take(180).ToArray();
        var framesSha256 = ComputeSha256(BuildCaptureFramesJsonl(orderedRows));
        var verdict = BuildReportVerdict(orderedRows);

        var html = new StringBuilder();
        html.AppendLine("<!doctype html>");
        html.AppendLine("<html lang=\"en\">");
        html.AppendLine("<head>");
        html.AppendLine("<meta charset=\"utf-8\" />");
        html.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />");
        html.AppendLine("<title>" + EscapeHtml(reportId) + "</title>");
        html.AppendLine(BuildReportCss());
        html.AppendLine("</head>");
        html.AppendLine("<body>");
        html.AppendLine("<main class=\"page\">");
        html.AppendLine("<section class=\"hero\">");
        html.AppendLine("<div>");
        html.AppendLine("<div class=\"eyebrow\">ARIEC60870 Evidence Analyzer</div>");
        html.AppendLine("<h1>IEC 60870 Evidence Report</h1>");
        html.AppendLine("<p>Professional protocol evidence summary for commissioning, FAT/SAT review, troubleshooting, and handover records.</p>");
        html.AppendLine("</div>");
        html.AppendLine("<div class=\"verdict " + EscapeHtml(verdict.CssClass) + "\">");
        html.AppendLine("<span>Verdict</span><strong>" + EscapeHtml(verdict.Status) + "</strong>");
        html.AppendLine("</div>");
        html.AppendLine("</section>");

        html.AppendLine("<section class=\"grid two\">");
        html.AppendLine(BuildInfoCard("Report", new[]
        {
            ("Report ID", reportId),
            ("Created", createdLocal.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture)),
            ("Source", sourceWorkspace),
            ("Protocol", protocolMode),
            ("Rows", orderedRows.Length.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("Sequence", $"{first.Sequence} → {last.Sequence}"),
            ("frames SHA256", framesSha256)
        }));
        html.AppendLine(BuildInfoCard("Session Counters", new[]
        {
            ("TX / RX", $"{_txCount} / {_rxCount}"),
            ("GI", _giCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("Class 1 / Class 2", $"{_class1Count} / {_class2Count}"),
            ("No data", _noDataCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("DPI/Event", _dpiCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("Active issues", CountActionableIssueRows().ToString(System.Globalization.CultureInfo.InvariantCulture))
        }));
        html.AppendLine("</section>");

        html.AppendLine("<section class=\"card\">");
        html.AppendLine("<h2>Communication Setup</h2>");
        html.AppendLine("<div class=\"kvlist\">");
        foreach (var line in setupLines)
        {
            html.AppendLine("<div><span>" + EscapeHtml(line.Key) + "</span><strong>" + EscapeHtml(line.Value) + "</strong></div>");
        }
        html.AppendLine("</div>");
        html.AppendLine("</section>");

        html.AppendLine("<section class=\"card\">");
        html.AppendLine("<h2>Summary Verdict</h2>");
        html.AppendLine("<p class=\"lead\">" + EscapeHtml(verdict.Summary) + "</p>");
        html.AppendLine("</section>");

        html.AppendLine(BuildEvidenceTable("GI Evidence", "General interrogation milestones and related protocol rows.", giRows));
        html.AppendLine(BuildEvidenceTable("Command Evidence", "Select/operate, ACTCON/ACTTERM, command feedback and related rows.", commandRows));
        html.AppendLine(BuildEvidenceTable("SOE / Event Evidence", "Spontaneous, digital/event, timestamp and quality-related rows.", soeRows));
        html.AppendLine(BuildEvidenceTable("Important Protocol Evidence", "Warnings, errors, quality issue, NACK/negative, timeout, mapped signals and selected important rows.", importantRows.Length > 0 ? importantRows : orderedRows.Take(120).ToArray()));

        html.AppendLine("<section class=\"card appendix\">");
        html.AppendLine("<h2>Report Notes</h2>");
        html.AppendLine("<ul>");
        html.AppendLine("<li>Review this summary against the approved project FAT/SAT procedure and signal mapping.</li>");
        html.AppendLine("<li>Keep the accompanying .ariec capture file when replayable frame evidence is required.</li>");
        html.AppendLine("</ul>");
        html.AppendLine("</section>");

        html.AppendLine("</main>");
        html.AppendLine("</body>");
        html.AppendLine("</html>");
        return html.ToString();
    }

    private IEnumerable<KeyValuePair<string, string>> BuildReportCommunicationSetupLines()
    {
        yield return new("Protocol", GetSelectedProtocolMode().ToString());
        yield return new("Transport", (TransportModeComboBox?.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "-");
        yield return new("Serial port", PortComboBox?.SelectedItem?.ToString() ?? "-");
        yield return new("Baud", string.IsNullOrWhiteSpace(BaudComboBox?.Text) ? ((BaudComboBox?.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "-") : BaudComboBox!.Text);
        yield return new("IEC104 host/port", $"{TcpHostBox?.Text}:{TcpPortBox?.Text}");
        yield return new("Link address", LinkAddressBox?.Text ?? "-");
        yield return new("Common address", CommonAddressBox?.Text ?? "-");
        yield return new("Link address size", (LinkAddressSizeComboBox?.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? LinkAddressSizeComboBox?.Text ?? "-");
        yield return new("COT / CA / IOA size", $"{(CotSizeComboBox?.SelectedItem as ComboBoxItem)?.Content ?? CotSizeComboBox?.Text} / {(CaSizeComboBox?.SelectedItem as ComboBoxItem)?.Content ?? CaSizeComboBox?.Text} / {(IoaSizeComboBox?.SelectedItem as ComboBoxItem)?.Content ?? IoaSizeComboBox?.Text}");
        yield return new("Class 2 interval", Class2IntervalBox?.Text ?? "-");
        yield return new("T0/T1/T2/T3", $"{Iec104T0Box?.Text}/{Iec104T1Box?.Text}/{Iec104T2Box?.Text}/{Iec104T3Box?.Text}");
        yield return new("K/W", $"{Iec104KBox?.Text}/{Iec104WBox?.Text}");
        yield return new("Mapping profile", string.IsNullOrWhiteSpace(SanitizeSavedMappingProfilePath(MappingProfilePathBox?.Text)) ? "-" : SanitizeSavedMappingProfilePath(MappingProfilePathBox?.Text));
    }

    private static string BuildReportCss()
        => """
<style>
:root{--ink:#111827;--muted:#64748b;--line:#dbe5f2;--panel:#f8fbff;--accent:#2563eb;--good:#15803d;--warn:#b45309;--bad:#b91c1c}
*{box-sizing:border-box}html{scrollbar-face-color:#94a3b8;scrollbar-track-color:#eef4fb;scrollbar-arrow-color:#64748b;scrollbar-shadow-color:#eef4fb;scrollbar-highlight-color:#eef4fb;scrollbar-3dlight-color:#eef4fb;scrollbar-darkshadow-color:#eef4fb}body{margin:0;background:#f3f7fc;color:var(--ink);font-family:Aptos,Segoe UI,Arial,sans-serif;font-size:12px;line-height:1.45;scrollbar-face-color:#94a3b8;scrollbar-track-color:#eef4fb;scrollbar-arrow-color:#64748b;scrollbar-shadow-color:#eef4fb;scrollbar-highlight-color:#eef4fb;scrollbar-3dlight-color:#eef4fb;scrollbar-darkshadow-color:#eef4fb}body::-webkit-scrollbar,.tablewrap::-webkit-scrollbar{width:10px;height:10px}body::-webkit-scrollbar-track,.tablewrap::-webkit-scrollbar-track{background:#eef4fb;border-radius:999px}body::-webkit-scrollbar-thumb,.tablewrap::-webkit-scrollbar-thumb{background:#94a3b8;border-radius:999px;border:2px solid #eef4fb}.page{max-width:1080px;margin:22px auto;padding:0 20px 32px}.hero{display:flex;justify-content:space-between;gap:18px;align-items:center;background:linear-gradient(135deg,#ffffff,#f7fbff);border:1px solid var(--line);border-left:5px solid var(--accent);border-radius:20px;padding:20px 22px;box-shadow:0 16px 40px rgba(15,23,42,.08)}.hero h1{margin:3px 0 6px;font-size:25px;letter-spacing:-.035em;font-weight:650}.hero p{margin:0;color:#475569;max-width:720px}.eyebrow{font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:#2563eb;font-weight:700}.verdict{min-width:144px;border-radius:16px;padding:12px;background:#f8fbff;border:1px solid var(--line);display:flex;flex-direction:column;justify-content:center;text-align:center}.verdict span{font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:var(--muted);font-weight:700}.verdict strong{font-size:22px;letter-spacing:-.03em}.verdict.pass strong{color:var(--good)}.verdict.attention strong{color:var(--warn)}.verdict.fail strong{color:var(--bad)}.grid{display:grid;gap:14px;margin-top:14px}.grid.two{grid-template-columns:1fr 1fr}.card{background:white;border:1px solid var(--line);border-radius:18px;padding:16px;margin-top:14px;box-shadow:0 10px 28px rgba(15,23,42,.06)}.card h2{margin:0 0 10px;font-size:15px;letter-spacing:-.02em;font-weight:650}.lead{font-size:13px;color:#334155;margin:0}.kvlist{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 14px}.kvlist div{border-bottom:1px solid #eef3f8;padding-bottom:7px}.kvlist span{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:700}.kvlist strong{display:block;margin-top:2px;font-weight:600;word-break:break-word}.tablewrap{overflow:auto;border:1px solid var(--line);border-radius:14px}table{width:100%;border-collapse:collapse;background:white}th,td{padding:8px 9px;border-bottom:1px solid #edf2f7;vertical-align:top;text-align:left}th{position:sticky;top:0;background:#f8fbff;font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#475569}td.mono{font-family:'Cascadia Mono','Consolas',monospace;font-size:11px}.muted{color:var(--muted)}.chip{display:inline-block;border-radius:999px;padding:2px 7px;background:#eff6ff;color:#1d4ed8;font-weight:700;font-size:10px}.empty{color:var(--muted);font-style:italic}.appendix ul{margin:0;padding-left:18px}@media print{body{background:white}.page{max-width:none;margin:0;padding:0}.hero,.card{box-shadow:none}.hero{border-radius:0}.card{break-inside:avoid}.tablewrap{overflow:visible}th{position:static}}
</style>
""";

    private static string BuildInfoCard(string title, IEnumerable<(string Key, string Value)> rows)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<section class=\"card\">");
        builder.AppendLine("<h2>" + EscapeHtml(title) + "</h2>");
        builder.AppendLine("<div class=\"kvlist\">");
        foreach (var row in rows)
        {
            builder.AppendLine("<div><span>" + EscapeHtml(row.Key) + "</span><strong>" + EscapeHtml(row.Value) + "</strong></div>");
        }
        builder.AppendLine("</div>");
        builder.AppendLine("</section>");
        return builder.ToString();
    }

    private static string BuildEvidenceTable(string title, string description, IReadOnlyList<EvidenceRow> rows)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<section class=\"card\">");
        builder.AppendLine("<h2>" + EscapeHtml(title) + "</h2>");
        builder.AppendLine("<p class=\"muted\">" + EscapeHtml(description) + "</p>");
        if (rows.Count == 0)
        {
            builder.AppendLine("<p class=\"empty\">No matching evidence rows in this capture/report scope.</p>");
        }
        else
        {
            builder.AppendLine("<div class=\"tablewrap\"><table>");
            builder.AppendLine("<thead><tr><th>#</th><th>Time</th><th>Dir</th><th>Service</th><th>CA/IOA</th><th>Type/COT</th><th>Quality</th><th>Meaning</th><th>Raw</th></tr></thead><tbody>");
            foreach (var row in rows)
            {
                builder.AppendLine("<tr>" +
                    "<td class=\"mono\">" + EscapeHtml(row.Sequence.ToString(System.Globalization.CultureInfo.InvariantCulture)) + "</td>" +
                    "<td class=\"mono\">" + EscapeHtml(row.Time) + "</td>" +
                    "<td><span class=\"chip\">" + EscapeHtml(row.Direction) + "</span></td>" +
                    "<td>" + EscapeHtml(row.ProtocolService) + "</td>" +
                    "<td class=\"mono\">" + EscapeHtml(row.CommonAddress + " / " + row.IoAddress) + "</td>" +
                    "<td>" + EscapeHtml(row.TypeId + " / " + row.CotDisplay) + "</td>" +
                    "<td>" + EscapeHtml(row.Quality) + "</td>" +
                    "<td>" + EscapeHtml(row.ProtocolTraceMeaning) + "</td>" +
                    "<td class=\"mono\">" + EscapeHtml(row.RawHex) + "</td>" +
                    "</tr>");
            }
            builder.AppendLine("</tbody></table></div>");
        }

        builder.AppendLine("</section>");
        return builder.ToString();
    }

    private static bool IsGiEvidenceRow(EvidenceRow row)
    {
        var text = BuildReportSearchText(row);
        return ContainsAny(text, "general interrogation", "interrogation", "GI ", "ACTCON", "ACTTERM");
    }

    private static bool IsCommandEvidenceRow(EvidenceRow row)
    {
        var text = BuildReportSearchText(row);
        return ContainsAny(text, "command", "select", "operate", "activation confirmation", "activation termination", "feedback", "C_SC", "C_DC", "C_SE");
    }

    private static bool IsSoeOrEventEvidenceRow(EvidenceRow row)
    {
        var text = BuildReportSearchText(row);
        return row.Mapped.Equals("Yes", StringComparison.OrdinalIgnoreCase)
               || ContainsAny(text, "spontaneous", "event", "digital", "single-point", "double-point", "timestamp", "soe");
    }

    private static bool IsReportImportantEvidenceRow(EvidenceRow row)
    {
        var text = BuildReportSearchText(row);
        return ContainsAny(text, "warning", "error", "negative", "nack", "timeout", "quality", "invalid", "not topical", "command", "interrogation", "spontaneous")
               || row.Mapped.Equals("Yes", StringComparison.OrdinalIgnoreCase);
    }

    private static string BuildReportSearchText(EvidenceRow row)
        => string.Join(" ", row.Category, row.State, row.ProtocolService, row.ProtocolTraceTitle, row.ProtocolTraceMeaning, row.Detail, row.CotDisplay, row.Quality, row.RawHex, row.SignalOrAddress, row.SemanticState);

    private static (string Status, string Summary, string CssClass) BuildReportVerdict(IReadOnlyList<EvidenceRow> rows, IReadOnlyList<EvidenceSmartFinding>? smartFindings = null)
    {
        if (smartFindings is not null && smartFindings.Any(finding => finding.Severity == EvidenceSmartFindingSeverity.Error))
        {
            var primary = smartFindings.First(finding => finding.Severity == EvidenceSmartFindingSeverity.Error);
            return ("ATTENTION", primary.Problem + " Follow the Smart Solution before accepting this test evidence.", "attention");
        }

        if (smartFindings is not null && smartFindings.Any(finding => finding.Severity == EvidenceSmartFindingSeverity.Warning))
        {
            var primary = smartFindings.First(finding => finding.Severity == EvidenceSmartFindingSeverity.Warning);
            return ("ATTENTION", primary.Problem + " Review the Smart Findings section and retest the affected path.", "attention");
        }

        var combined = string.Join(" ", rows.Select(BuildReportSearchText));
        if (ContainsAny(combined, "error", "timeout", "failed", "negative", "nack"))
        {
            return ("ATTENTION", "The evidence set contains protocol errors, timeout, negative confirmation, or NACK symptoms. Review the highlighted sections before accepting the test result.", "attention");
        }

        if (rows.Any(IsGiEvidenceRow) && rows.Any(IsSoeOrEventEvidenceRow))
        {
            return ("PASS", "GI and event evidence are present in the selected report scope. Review the point coverage and timestamp sections for final acceptance.", "pass");
        }

        return ("ATTENTION", "Evidence exists but is not sufficient for a full automatic pass verdict. Complete GI, event/SOE, and command feedback evidence may still be required.", "attention");
    }

    private static string EscapeHtml(string? value)
        => (value ?? string.Empty)
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal)
            .Replace("\"", "&quot;", StringComparison.Ordinal)
            .Replace("'", "&#39;", StringComparison.Ordinal);

}
