// Copyright 2026 Ari Sulistiono
// SPDX-License-Identifier: Apache-2.0

using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.IO.Compression;
using System.IO.Ports;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using ARIEC60870.Core.Mapping;
using ARIEC60870.Core.Model;
using ARIEC60870.Desktop.ViewModels;
using ARIEC60870.Master;
using ARIEC60870.Master.Model;
using ARIEC60870.Master.Reporting;
using ARIEC60870.Master.Transport;
using Microsoft.Win32;

namespace ARIEC60870.Desktop;

public partial class MainWindow
{
    private string AppendEvidenceRetentionPolicy(string markdown)
    {
        var builder = new StringBuilder(markdown ?? string.Empty);
        if (builder.Length > 0 && !builder.ToString().EndsWith(Environment.NewLine, StringComparison.Ordinal))
        {
            builder.AppendLine();
        }

        builder.AppendLine();
        builder.AppendLine("## Evidence Retention / UI Store Policy");
        builder.AppendLine();
        foreach (var line in BuildEvidenceRetentionPolicyLines())
        {
            builder.AppendLine("- " + line);
        }

        builder.AppendLine();
        builder.AppendLine("> This section is generated by the UI runtime. It describes evidence retention, trace suppression, low-value compression, and dispatcher pressure at export time.");
        return builder.ToString();
    }

    private string BuildTextEvidenceRetentionHeader(string exportName)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# ARIEC60870 export integrity marker");
        builder.AppendLine("# Export: " + exportName);
        foreach (var line in BuildEvidenceRetentionPolicyLines())
        {
            builder.AppendLine("# " + line);
        }
        builder.AppendLine("#");
        return builder.ToString();
    }

    private IEnumerable<string> BuildEvidenceRetentionPolicyLines()
    {
        yield return $"Protocol Trace mode: {GetTraceVerbosityMode()}";
        yield return $"Trace ring visible/stored: {FrameTraceRows.Count}/{MaxVisibleFrameTraceRows}";
        yield return $"Evidence Summary ring visible/stored: {EvidenceRows.Count}/{MaxVisibleEvidenceRows}";
        yield return $"Value store visible/keyed limit: {ValueRows.Count}/{MaxVisibleValueRows}";
        yield return $"Event Log ring visible/stored: {RelayEventRows.Count}/{MaxVisibleRelayEventRows}";
        yield return $"Diagnostics ring visible/stored: {DiagnosticRows.Count}/{MaxVisibleDiagnosticRows}";
        yield return $"Trace verbosity suppressed rows: total={_traceVerbositySuppressedRows}, routine={_traceVerbositySuppressedRoutine}, supervisory={_traceVerbositySuppressedSupervisory}";
        yield return $"Backpressure low-value compression: total={_backpressureDroppedEvents}, ack/no-data={_backpressureDroppedAckNoData}, background-poll={_backpressureDroppedBackgroundPoll}, test/supervisory={_backpressureDroppedTestFrames}, other={_backpressureDroppedOtherLowValue}";
        yield return $"Dispatcher queue: current={_pendingEvidence.Count}, maxObserved={_maxPendingEvidenceDepth}, adaptiveBudget={_lastFlushBudget}";
        yield return $"Dispatcher flush: last={_lastUiFlushMs} ms, max={_maxUiFlushMs} ms, ticks={_uiFlushTicks}, lastProcessed={_lastEvidenceProcessed}+{_lastFindingProcessed}, lastVisibleBatchRows={_lastVisibleBatchRows}";
        yield return $"Protocol proof state: CA={(_proofObservedCa > 0 ? _proofObservedCa.ToString(System.Globalization.CultureInfo.InvariantCulture) : "-")}, GI={_proofGiObserved}, GIComplete={_proofGiCompleted}, GINegative={_proofGiNegative}, Digital={_proofDigitalObserved}, Analog={_proofAnalogObserved}, Command={_proofCommandObserved}, CommandFeedback={_proofCommandFeedbackObserved}";
        yield return $"GI coverage matrix: monitor={_lastMonitorReceivedCount}/{_lastMonitorExpectedCount}, digital={_lastDigitalReceivedCount}/{_lastDigitalExpectedCount}, analog={_lastAnalogReceivedCount}/{_lastAnalogExpectedCount}, other={_lastOtherReceivedCount}/{_lastOtherExpectedCount}, missing={_lastMissingMonitorCount}, missingPreview={_lastMissingMonitorPreview}";
        yield return $"Command mapping coverage: commands={_lastCommandExpectedCount}, feedbackMapped={_lastFeedbackMappedCommandCount}";
        yield return "Protected evidence policy: diagnostics/warnings/errors, mapped values, process values, digital values, GI activity, command ASDUs, ACTCON and ACTTERM are protected from low-value trace compression.";
    }

    private void AddEvidenceRetentionExportMarker(string exportTarget)
    {
        AddUiDiagnostic(
            "Info",
            "Evidence",
            "ARIEC-EVIDENCE-RETENTION-POLICY",
            "Evidence export includes retention policy marker",
            $"{exportTarget} captured TraceMode={GetTraceVerbosityMode()}, traceSkip={_traceVerbositySuppressedRows}, lowValueDropped={_backpressureDroppedEvents}, qMax={_maxPendingEvidenceDepth}, maxFlush={_maxUiFlushMs} ms.",
            "Use this marker when reviewing FAT/SAT evidence so compressed routine trace rows are not mistaken for missing protocol evidence.");
    }



    private bool IsReportPreviewTabActive()
        => MainTabControl?.SelectedIndex == 6;

    private void RefreshReportPreview_Click(object sender, RoutedEventArgs e)
    {
        RefreshReportPreview();
    }

    private void RefreshReportPreview()
    {
        if (ReportPreviewBrowser is null)
        {
            return;
        }

        var html = BuildCurrentReportPreviewHtml();
        ReportPreviewBrowser.NavigateToString(html);
    }

    private IReadOnlyList<EvidenceRow> GetCurrentReportRows(out string sourceWorkspace)
    {
        var selectedRows = GetSelectedRowsForUnifiedEvidenceCapture(out sourceWorkspace);
        if (selectedRows.Count > 0)
        {
            return selectedRows;
        }

        var protocolRows = _protocolTraceStore.Snapshot();
        if (protocolRows.Count > 0)
        {
            sourceWorkspace = "ProtocolTrace";
            return protocolRows;
        }

        if (EvidenceRows.Count > 0)
        {
            sourceWorkspace = "EvidenceSummary";
            return EvidenceRows.ToArray();
        }

        sourceWorkspace = "CurrentEvidenceBuffer";
        return Array.Empty<EvidenceRow>();
    }

    private string BuildCurrentReportPreviewHtml()
    {
        var rows = GetCurrentReportRows(out var sourceWorkspace);
        var created = DateTime.Now;
        if (rows.Count == 0)
        {
            return BuildEmptyReportPreviewHtml(created);
        }

        return BuildEvidenceHtmlReport("ARIEC-REPORT-PREVIEW", created, rows, sourceWorkspace);
    }

    private string BuildEmptyReportPreviewHtml(DateTime createdLocal)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\" />");
        builder.AppendLine("<title>ARIEC Report Preview</title>");
        builder.AppendLine(BuildReportCss());
        builder.AppendLine("</head><body><main class=\"page\">");
        builder.AppendLine("<section class=\"hero\"><div><div class=\"eyebrow\">ARIEC60870 Protocol Lab</div><h1>Report Preview</h1><p>No evidence rows are available yet. Run an IEC session, open a .ariec capture, or select evidence rows first.</p></div><div class=\"verdict attention\"><span>Status</span><strong>EMPTY</strong></div></section>");
        builder.AppendLine("<section class=\"card\"><h2>How to use</h2><ul><li>Run or open capture evidence.</li><li>Review Protocol Trace / Evidence Summary.</li><li>Return here and click Refresh.</li><li>Click Export HTML / PDF, open the HTML in browser, then print to PDF.</li></ul></section>");
        builder.AppendLine("<section class=\"card\"><h2>Generated</h2><p>" + EscapeHtml(createdLocal.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture)) + "</p></section>");
        builder.AppendLine("</main></body></html>");
        return builder.ToString();
    }

    private void ExportMarkdown_Click(object sender, RoutedEventArgs e)
    {
        var rows = GetCurrentReportRows(out var sourceWorkspace);

        if (rows.Count == 0)
        {
            MessageBox.Show(this, "No evidence rows are available yet. Run or open a capture first.", "Export report", MessageBoxButton.OK, MessageBoxImage.Information);
            return;
        }

        var created = DateTime.Now;
        var reportId = "ARIEC-REPORT-" + created.ToString("yyyyMMdd-HHmmss", System.Globalization.CultureInfo.InvariantCulture);
        var dialog = new SaveFileDialog
        {
            Title = "Export protocol evidence report",
            Filter = "HTML report (*.html)|*.html|All files (*.*)|*.*",
            FileName = $"{reportId}.html",
            AddExtension = true,
            DefaultExt = ".html"
        };

        if (dialog.ShowDialog(this) != true)
        {
            return;
        }

        var html = BuildEvidenceHtmlReport(reportId, created, rows, sourceWorkspace);
        File.WriteAllText(dialog.FileName, html, Encoding.UTF8);
        AddEvidenceRetentionExportMarker("protocol HTML evidence report");
        AppendSessionLog("protocol HTML evidence report exported: " + dialog.FileName);
        MessageBox.Show(this, "HTML evidence report exported successfully. Open it in a browser and print to PDF when needed.", "Export report", MessageBoxButton.OK, MessageBoxImage.Information);
    }

    private string BuildEvidenceHtmlReport(string reportId, DateTime createdLocal, IReadOnlyList<EvidenceRow> rows, string sourceWorkspace)
    {
        var orderedRows = rows.OrderBy(row => row.Sequence).ToArray();
        var first = orderedRows.First();
        var last = orderedRows.Last();
        var protocolMode = GetSelectedProtocolMode().ToString();
        var setupLines = BuildReportCommunicationSetupLines();
        var giRows = orderedRows.Where(IsGiEvidenceRow).Take(80).ToArray();
        var commandRows = orderedRows.Where(IsCommandEvidenceRow).Take(80).ToArray();
        var soeRows = orderedRows.Where(IsSoeOrEventEvidenceRow).Take(120).ToArray();
        var importantRows = orderedRows.Where(IsReportImportantEvidenceRow).Take(180).ToArray();
        var framesSha256 = ComputeSha256(BuildCaptureFramesJsonl(orderedRows));
        var verdict = BuildReportVerdict(orderedRows);

        var html = new StringBuilder();
        html.AppendLine("<!doctype html>");
        html.AppendLine("<html lang=\"en\">");
        html.AppendLine("<head>");
        html.AppendLine("<meta charset=\"utf-8\" />");
        html.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />");
        html.AppendLine("<title>" + EscapeHtml(reportId) + "</title>");
        html.AppendLine(BuildReportCss());
        html.AppendLine("</head>");
        html.AppendLine("<body>");
        html.AppendLine("<main class=\"page\">");
        html.AppendLine("<section class=\"hero\">");
        html.AppendLine("<div>");
        html.AppendLine("<div class=\"eyebrow\">ARIEC60870 Protocol Lab</div>");
        html.AppendLine("<h1>IEC 60870 Evidence Report</h1>");
        html.AppendLine("<p>Protocol communication test evidence generated from the current ARIEC evidence buffer. This file is standalone and can be opened without ARIEC.</p>");
        html.AppendLine("</div>");
        html.AppendLine("<div class=\"verdict " + EscapeHtml(verdict.CssClass) + "\">");
        html.AppendLine("<span>Verdict</span><strong>" + EscapeHtml(verdict.Status) + "</strong>");
        html.AppendLine("</div>");
        html.AppendLine("</section>");

        html.AppendLine("<section class=\"grid two\">");
        html.AppendLine(BuildInfoCard("Report", new[]
        {
            ("Report ID", reportId),
            ("Created", createdLocal.ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture)),
            ("Source", sourceWorkspace),
            ("Protocol", protocolMode),
            ("Rows", orderedRows.Length.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("Sequence", $"{first.Sequence} → {last.Sequence}"),
            ("frames SHA256", framesSha256)
        }));
        html.AppendLine(BuildInfoCard("Session Counters", new[]
        {
            ("TX / RX", $"{_txCount} / {_rxCount}"),
            ("GI", _giCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("Class 1 / Class 2", $"{_class1Count} / {_class2Count}"),
            ("No data", _noDataCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("DPI/Event", _dpiCount.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("Findings", FindingRows.Count.ToString(System.Globalization.CultureInfo.InvariantCulture))
        }));
        html.AppendLine("</section>");

        html.AppendLine("<section class=\"card\">");
        html.AppendLine("<h2>Communication Setup</h2>");
        html.AppendLine("<div class=\"kvlist\">");
        foreach (var line in setupLines)
        {
            html.AppendLine("<div><span>" + EscapeHtml(line.Key) + "</span><strong>" + EscapeHtml(line.Value) + "</strong></div>");
        }
        html.AppendLine("</div>");
        html.AppendLine("</section>");

        html.AppendLine("<section class=\"card\">");
        html.AppendLine("<h2>Summary Verdict</h2>");
        html.AppendLine("<p class=\"lead\">" + EscapeHtml(verdict.Summary) + "</p>");
        html.AppendLine("</section>");

        html.AppendLine(BuildEvidenceTable("GI Evidence", "General interrogation milestones and related protocol rows.", giRows));
        html.AppendLine(BuildEvidenceTable("Command Evidence", "Select/operate, ACTCON/ACTTERM, command feedback and related rows.", commandRows));
        html.AppendLine(BuildEvidenceTable("SOE / Event Evidence", "Spontaneous, digital/event, timestamp and quality-related rows.", soeRows));
        html.AppendLine(BuildEvidenceTable("Important Protocol Evidence", "Warnings, errors, quality issue, NACK/negative, timeout, mapped signals and selected important rows.", importantRows.Length > 0 ? importantRows : orderedRows.Take(120).ToArray()));

        html.AppendLine("<section class=\"card appendix\">");
        html.AppendLine("<h2>Report Notes</h2>");
        html.AppendLine("<ul>");
        html.AppendLine("<li>This report is generated from ARIEC evidence rows and does not require the ARIEC application to be opened.</li>");
        html.AppendLine("<li>Use browser print to save as PDF for FAT/SAT evidence attachment.</li>");
        html.AppendLine("<li>For full replayable evidence, keep the accompanying .ariec capture file.</li>");
        html.AppendLine("</ul>");
        html.AppendLine("</section>");

        html.AppendLine("</main>");
        html.AppendLine("</body>");
        html.AppendLine("</html>");
        return html.ToString();
    }

    private IEnumerable<KeyValuePair<string, string>> BuildReportCommunicationSetupLines()
    {
        yield return new("Protocol", GetSelectedProtocolMode().ToString());
        yield return new("Transport", (TransportModeComboBox?.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "-");
        yield return new("Serial port", PortComboBox?.SelectedItem?.ToString() ?? "-");
        yield return new("Baud", (BaudComboBox?.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "-");
        yield return new("IEC104 host/port", $"{TcpHostBox?.Text}:{TcpPortBox?.Text}");
        yield return new("Link address", LinkAddressBox?.Text ?? "-");
        yield return new("Common address", CommonAddressBox?.Text ?? "-");
        yield return new("COT / CA / IOA size", $"{(CotSizeComboBox?.SelectedItem as ComboBoxItem)?.Content} / {(CaSizeComboBox?.SelectedItem as ComboBoxItem)?.Content} / {(IoaSizeComboBox?.SelectedItem as ComboBoxItem)?.Content}");
        yield return new("T0/T1/T2/T3", $"{Iec104T0Box?.Text}/{Iec104T1Box?.Text}/{Iec104T2Box?.Text}/{Iec104T3Box?.Text}");
        yield return new("K/W", $"{Iec104KBox?.Text}/{Iec104WBox?.Text}");
        yield return new("Mapping profile", string.IsNullOrWhiteSpace(MappingProfilePathBox?.Text) ? "-" : MappingProfilePathBox.Text);
    }

    private static string BuildReportCss()
        => """
<style>
:root{--ink:#111827;--muted:#64748b;--line:#dbe5f2;--panel:#f8fbff;--accent:#2563eb;--good:#16a34a;--warn:#d97706;--bad:#dc2626}
*{box-sizing:border-box}body{margin:0;background:#eaf1fb;color:var(--ink);font-family:Aptos,Segoe UI,Arial,sans-serif;font-size:13px;line-height:1.45}.page{max-width:1180px;margin:28px auto;padding:0 22px 36px}.hero{display:flex;justify-content:space-between;gap:24px;align-items:stretch;background:linear-gradient(135deg,#0f172a,#1d4ed8);color:white;border-radius:24px;padding:30px 34px;box-shadow:0 24px 60px rgba(15,23,42,.24)}.hero h1{margin:4px 0 8px;font-size:32px;letter-spacing:-.04em}.hero p{margin:0;color:#dbeafe;max-width:720px}.eyebrow{font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#bfdbfe;font-weight:700}.verdict{min-width:180px;border-radius:20px;padding:18px;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.22);display:flex;flex-direction:column;justify-content:center;text-align:center}.verdict span{font-size:11px;text-transform:uppercase;letter-spacing:.14em;color:#dbeafe}.verdict strong{font-size:28px;letter-spacing:-.03em}.verdict.pass strong{color:#86efac}.verdict.attention strong{color:#fde68a}.verdict.fail strong{color:#fecaca}.grid{display:grid;gap:16px;margin-top:16px}.grid.two{grid-template-columns:1fr 1fr}.card{background:white;border:1px solid var(--line);border-radius:20px;padding:20px;margin-top:16px;box-shadow:0 12px 32px rgba(15,23,42,.08)}.card h2{margin:0 0 12px;font-size:18px;letter-spacing:-.02em}.lead{font-size:14px;color:#334155;margin:0}.kvlist{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 16px}.kvlist div{border-bottom:1px solid #eef3f8;padding-bottom:8px}.kvlist span{display:block;font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:700}.kvlist strong{display:block;margin-top:3px;font-weight:600;word-break:break-word}.tablewrap{overflow:auto;border:1px solid var(--line);border-radius:14px}table{width:100%;border-collapse:collapse;background:white}th,td{padding:9px 10px;border-bottom:1px solid #edf2f7;vertical-align:top;text-align:left}th{position:sticky;top:0;background:#f8fbff;font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#475569}td.mono{font-family:'Cascadia Mono','Consolas',monospace;font-size:12px}.muted{color:var(--muted)}.chip{display:inline-block;border-radius:999px;padding:3px 8px;background:#eff6ff;color:#1d4ed8;font-weight:700;font-size:11px}.empty{color:var(--muted);font-style:italic}.appendix ul{margin:0;padding-left:18px}@media print{body{background:white}.page{max-width:none;margin:0;padding:0}.hero,.card{box-shadow:none}.hero{border-radius:0}.card{break-inside:avoid}.tablewrap{overflow:visible}th{position:static}}
</style>
""";

    private static string BuildInfoCard(string title, IEnumerable<(string Key, string Value)> rows)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<section class=\"card\">");
        builder.AppendLine("<h2>" + EscapeHtml(title) + "</h2>");
        builder.AppendLine("<div class=\"kvlist\">");
        foreach (var row in rows)
        {
            builder.AppendLine("<div><span>" + EscapeHtml(row.Key) + "</span><strong>" + EscapeHtml(row.Value) + "</strong></div>");
        }
        builder.AppendLine("</div>");
        builder.AppendLine("</section>");
        return builder.ToString();
    }

    private static string BuildEvidenceTable(string title, string description, IReadOnlyList<EvidenceRow> rows)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<section class=\"card\">");
        builder.AppendLine("<h2>" + EscapeHtml(title) + "</h2>");
        builder.AppendLine("<p class=\"muted\">" + EscapeHtml(description) + "</p>");
        if (rows.Count == 0)
        {
            builder.AppendLine("<p class=\"empty\">No matching evidence rows in this capture/report scope.</p>");
        }
        else
        {
            builder.AppendLine("<div class=\"tablewrap\"><table>");
            builder.AppendLine("<thead><tr><th>#</th><th>Time</th><th>Dir</th><th>Service</th><th>CA/IOA</th><th>Type/COT</th><th>Quality</th><th>Meaning</th><th>Raw</th></tr></thead><tbody>");
            foreach (var row in rows)
            {
                builder.AppendLine("<tr>" +
                    "<td class=\"mono\">" + EscapeHtml(row.Sequence.ToString(System.Globalization.CultureInfo.InvariantCulture)) + "</td>" +
                    "<td class=\"mono\">" + EscapeHtml(row.Time) + "</td>" +
                    "<td><span class=\"chip\">" + EscapeHtml(row.Direction) + "</span></td>" +
                    "<td>" + EscapeHtml(row.ProtocolService) + "</td>" +
                    "<td class=\"mono\">" + EscapeHtml(row.CommonAddress + " / " + row.IoAddress) + "</td>" +
                    "<td>" + EscapeHtml(row.TypeId + " / " + row.CotDisplay) + "</td>" +
                    "<td>" + EscapeHtml(row.Quality) + "</td>" +
                    "<td>" + EscapeHtml(row.ProtocolTraceMeaning) + "</td>" +
                    "<td class=\"mono\">" + EscapeHtml(row.RawHex) + "</td>" +
                    "</tr>");
            }
            builder.AppendLine("</tbody></table></div>");
        }

        builder.AppendLine("</section>");
        return builder.ToString();
    }

    private static bool IsGiEvidenceRow(EvidenceRow row)
    {
        var text = BuildReportSearchText(row);
        return ContainsAny(text, "general interrogation", "interrogation", "GI ", "ACTCON", "ACTTERM");
    }

    private static bool IsCommandEvidenceRow(EvidenceRow row)
    {
        var text = BuildReportSearchText(row);
        return ContainsAny(text, "command", "select", "operate", "activation confirmation", "activation termination", "feedback", "C_SC", "C_DC", "C_SE");
    }

    private static bool IsSoeOrEventEvidenceRow(EvidenceRow row)
    {
        var text = BuildReportSearchText(row);
        return row.Mapped.Equals("Yes", StringComparison.OrdinalIgnoreCase)
               || ContainsAny(text, "spontaneous", "event", "digital", "single-point", "double-point", "timestamp", "soe");
    }

    private static bool IsReportImportantEvidenceRow(EvidenceRow row)
    {
        var text = BuildReportSearchText(row);
        return ContainsAny(text, "warning", "error", "negative", "nack", "timeout", "quality", "invalid", "not topical", "command", "interrogation", "spontaneous")
               || row.Mapped.Equals("Yes", StringComparison.OrdinalIgnoreCase);
    }

    private static string BuildReportSearchText(EvidenceRow row)
        => string.Join(" ", row.Category, row.State, row.ProtocolService, row.ProtocolTraceTitle, row.ProtocolTraceMeaning, row.Detail, row.CotDisplay, row.Quality, row.RawHex, row.SignalOrAddress, row.SemanticState);

    private static (string Status, string Summary, string CssClass) BuildReportVerdict(IReadOnlyList<EvidenceRow> rows)
    {
        var combined = string.Join(" ", rows.Select(BuildReportSearchText));
        if (ContainsAny(combined, "error", "timeout", "failed", "negative", "nack"))
        {
            return ("ATTENTION", "The evidence set contains protocol errors, timeout, negative confirmation, or NACK symptoms. Review the highlighted sections before accepting the test result.", "attention");
        }

        if (rows.Any(IsGiEvidenceRow) && rows.Any(IsSoeOrEventEvidenceRow))
        {
            return ("PASS", "GI and event evidence are present in the selected report scope. Review the point coverage and timestamp sections for final acceptance.", "pass");
        }

        return ("ATTENTION", "Evidence exists but is not sufficient for a full automatic pass verdict. Complete GI, event/SOE, and command feedback evidence may still be required.", "attention");
    }

    private static string EscapeHtml(string? value)
        => (value ?? string.Empty)
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal)
            .Replace("\"", "&quot;", StringComparison.Ordinal)
            .Replace("'", "&#39;", StringComparison.Ordinal);

}
